#!/usr/bin/env bash
# install load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  kmishmael-frontend
        bind *:80
        mode http
        default_backend kmishmael-backend
backend kmishmael-backend
        balance roundrobin
        server 229883-web-01 52.204.97.3:80 check
        server 229883-web-02 54.237.96.136:80 check
"
sudo echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart