#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
s="\
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend web-frontend
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 229883-web-01 52.204.97.3:80 check
    server 229883-web-02 54.237.96.136:80 check
"
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

command -v haproxy &> /dev/null

#shellcheck disable=SC2181
if [ $? -ne 0 ]; then
	echo -e "	Installing: haproxy\n"
	sudo apt-get update -y -qq && \
		sudo apt-get install -y haproxy -qq
	echo -e "\n"
else
	echo -e "	haproxy is already installed.\n"
fi

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# shellcheck disable=SC2154
echo "$s" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi

echo -e "	Finished excuting script.\n"